InsightRX/PKPDsim

R/apply_lagtime.R, tests/testthat/test_apply_lagtime.R
A bug was present when lagtime was specified as a parameter in a model (e.g. TLAG), and the lag time definition specified as a vector for the compartments, e.g. `["TLAG", 0, 0]`. This caused the lag-time not to be applied. This PR fixes that behavior and updates unit tests to include that scenario.
=> RXR-602 fix issue lag time for models with multiple compartments

DESCRIPTION, R/apply_lagtime.R, R/sim.R, man/apply_lagtime.Rd, src/RcppExports.cpp, tests/testthat/test_apply_lagtime.R
We have to supply cmt_mapping that is tied to the model as well, otherwise lag times are not supplied to the correct compartments
=> RXR-602 more fixes to lagtime implementation

R/create_event_table.R, R/sim.R, tests/testthat/test_create_event_table.R
When a simulation was performed with multiple observation types *and* on of the specified observation times coincided with an infusion stop event, the infusion stop event would be repeated due to a merge action. This resulted in negative infusion rates.
=> RXR-616: fix bug multiple infusion stop events

src/Makevars
Requires trick described here:
http://dirk.eddelbuettel.com/blog/2017/08/14/#009_compact_shared_libraries
https://stackoverflow.com/questions/46280628/object-files-in-r-package-too-large-rcpp
With the Makevars file, the NOTE about pkg size is not thrown anymore.
=> RXR-639 reduce package size (strip libs)

tests/testthat/test_advan_with_auc.R, tests/testthat/test_advan_with_covariates.R, tests/testthat/test_bioav_def.R, tests/testthat/test_calc_ss_analytic.R, tests/testthat/test_cmt_mapping.R, tests/testthat/test_get_var_y.R, tests/testthat/test_iov.R, tests/testthat/test_parameters_table.R, tests/testthat/test_pkpd_combined.R, tests/testthat/test_t_init.R, tests/testthat/test_timevar_cov.R
Some of our tests are relatively slow, often due to calls to `new_ode_model()`. This skips some tests on CRAN and rearranges some of the test code to put it within `test_that()` calls (so it can be easily skipped). In `test_advan_with_auc.R` there's a lot of code outside of `test_that()` calls that gets reused in multiple tests, so rather than duplicate it I put it in an `if` clause that checks for the `NOT_CRAN` environment variable. This is the same approach taken by `skip_on_cran()`, so I think it should be reasonable.
On my machine, `devtools::check(env_vars = c("NOT_CRAN" = "false"))` reports that the test suite takes 54 seconds. It's possible results will be different on CRAN machines depending on their load, but there's no real way to be certain until we try, so I think this is …
=> RXR-635: Skip slow tests on CRAN

inst/cpp/sim.cpp
In the previous PR (https://github.com/InsightRX/PKPDsim/pull/29/files), initialization of `prv_dose` and `t_prv_dos` was added, but by mistake this initialization was placed inside the main loop over the event table, and not before. This PR fixes that.
This would only have affected models that use `t_prv_dose` or `prv_dose` in their model code.
=> RXR-792: fix placement of var init

inst/cpp/sim.cpp, tests/testthat/test_iov.R
Because of the order of code in the sim.cpp, IOV defined in the PK block wasn’t called at the right times to actually affect biovailability properly. Requires a small change of order of code execution in the main loop in sim.cpp. 
Check that it doesn’t affect other models: in progress
Add a unit test: haven't been able yet to create a unit test that catches the error.
=> slight re-order of C++ code in main loop to make sure IOV on bioavailability is correctly applied

R/sim.R, tests/testthat/test_sim_lagtime.R
For some models with lagtimes for oral drugs, the amounts in compartment 1 will show a spike, due to the erroneous re-ordering of the output after simulation. The cause is a merge() command that altered the order of the output from the simulater. No “wrong” concentrations were simulated for any model, it’s just the output that was in some cases not arranged correctly.
=> RXR-837 fix order output for models with lagtime

Jenkinsfile
The PKPDsim source code is in `/src` but the latest irx-r-base image changes the working directory to something else, so I've updated the jenkinsfile here to run `devtools::check()` with the absolute path.
=> RXR-982: Run check in correct directory

R/new_covariate.R, man/new_covariate.Rd, tests/testthat/test_new_covariate.R
This adds a feature to perform rounding of covariate times. This is especially useful in production code when assuming a certain precision for regimens, TDMs, and covariate times.
=> RXR-927 allow rounding to be specified in new_covariate()

R/model_from_api.R
Minor update to our logic for checking the `build` field.  If the `build` field is missing, `model_from_api()` would error. I don't think we necessarily want to require this field in the public versions of our models, so I'm using `isTRUE()` to avoid the error.
=> RXR-973: Use isTRUE when checking whether to build

R/create_event_table.R, R/parse_obs_types.R, inst/cpp/sim.cpp, tests/testthat/test_multi_obs.R, tests/testthat/test_parse_obs_types.R
As far as I can tell, the issue only surfaces when we have:
- a variable that has a basline
- observation at t=0, or observation equal to dose time
- multiple observation types
There was an indexing issue in C that caused the wrong value to be exported. Also, in R, an issue with double dosing occurred with multiple observation types and t_obs at same time of dosing.
=> RXR-1014 fix issue with multiple observation types

.github/workflows/pkgdown.yaml
pkgdown started failing after #46, I updated to the latest version of the `setup-r` and `setup-r-dependencies` actions and that seems to have resolved it.
=> RXR-1050: Fix github actions

.github/workflows/pkgdown.yaml
pkgdown is still failing on master after #49. I updated my version of usethis and re-ran `use_pkgdown_github_pages()`, which now generates a slightly different version of the pkgdown github action. Hopefully this should work better; if nothing else it will run (but not deploy) on pull requests, so it should be easier to tell before merging if we'll be able to build the site or not.
=> RXR-1050: Use updated pkgdown action

R/join_regimen.R, tests/testthat/test_join_regimen.R
When a drug is oral or SC administered, it will not have a t_inf specified. This PR fixes the behavior and adds a test.
=> RXR-1228 fix bug when joining regimens with no t_inf

R/misc.R, tests/testthat/test_misc.R
This will allow us to list development info as `"development": {}` in the model json in cases where the development population isn't known.
=> RXR-1298: allow empty lists in print_list()

DESCRIPTION, NAMESPACE, R/misc.R, R/new_ode_model.R, man/print_list.Rd, tests/testthat/test_misc.R
`print_list()`'s quoting behavior did not work well on nested lists:
```r
dat <- list(a = list(b = "foo"), c = "bar")
print_list(dat)
#> [1] "list (\"a\" = list(b = \"foo\"), \"c\" = bar)" # needs quotes around "bar" to be valid R syntax
print_list(dat, quote = TRUE)
#> [1] "list (\"a\" = \"list(b = \"foo\")\", \"c\" = \"bar\")" # quotes around the second list( shouldn't be there
``` 
It seems like this function only really worked well on lists that were a) not nested and b) all of the same type. A more flexible approach was to rewrite it using `capture.output()` and `dput()`. I was able to install all the model packages and run all our downstream f-tests after this change.
I've implemented this as an S3 method for lists and NULL values only, on the thinking that `dput()` output may not …
=> Rewrite print_list

R/get_fixed_parameters.R, man/get_fixed_parameters.Rd, tests/testthat/sample_json/test_1cmt_iv.json5, tests/testthat/test_get_fixed_parameters.R
This reverses the changes in #66; we now require `"fixed"` to be present in the model definition.
=> RXR-1379: require fixed parameters in model definition

PKPDsim.Rproj, R/regimen_to_nm.R, man/regimen_to_nm.Rd, tests/testthat/test_regimen_to_nm.R
PKPDsim automatically applies the bioavailability to infusions. NONMEM doesn’t do that, it instead recalculates duration as ((AMT/bioav)*rate), and then uses the given RATE to infuse. So for bioavailability of 10%, the duration will be 10 times shorter. But that's generally not really what one wants. The more intuitive way is to  just multiple RATE by bioavailability.
Generally we only have a bioavailability factor for oral models, which use a bolus into a dose compartment, so this issue will never surface. However, sometimes there is a use case for IV models too, e.g. when using it to convert unit from mg to mmol, or drug to prodrug. NONMEM's behavior with this scenario is also explained in the [RxODE manual](https://nlmixrdevelopment.github.io/RxODE-manual/events.html), as RxODE matches …
=> RXR-1470: circumvent difference in how NONMEM and PKPDsim handle bioavailability for infusions

R/new_ode_model.R
```
Warning message:
In matrix(c("\\[MODULE\\]", package, "\\[N_COMP\\]", size, "\\[OBS_COMP\\]",  :
data length [55] is not a sub-multiple or multiple of the number of rows [28]
```
See command in JIRA ticket. No test needed, very minor fix.
=> RXR-1539: bug: if link to "nonmem" file not defined in model, showing an uncaught warning

R/new_covariate.R
Elsewhere in the code we make messages conditional on the `verbose` argument. I've added that to this line to make this function quieter.
=> RXR-1526: Only message about time for first covariate measurement if verbose

R/compile_sim_cpp.R, inst/cpp/sim.cpp, tests/testthat/test_t_init.R
When state A is initialized manually and is not [0, 0, 0, ...], we also want to have variables that depend on this initial state updated. This was not done, except for the standard observation variable `y`. We need this whenever we use a non-default concentration observation, e.g. CONC or CONCF.
=> IRX-5176 fix variables have value at first row

src/pk_1cmt_iv_bolus.cpp, src/pk_1cmt_iv_bolus_covariates.cpp, src/pk_1cmt_iv_infusion.cpp, src/pk_1cmt_oral.cpp, src/pk_2cmt_iv_bolus.cpp, src/pk_2cmt_iv_infusion.cpp, src/pk_2cmt_oral.cpp, src/pk_3cmt_iv_bolus.cpp, src/pk_3cmt_iv_infusion.cpp, src/pk_3cmt_oral.cpp
This just fixes some warnings that were thrown during the compilation of the hardcoded linear compartmental models included with PKPDsim. The warnings were harmless, mostly just declaration of unused variables, so this is just cleanup.
The warnings only showed when installing PKPDsim from scratch, or when running `R CMD INSTALL . --preclean`.
On my local machine:
```
clang++ -mmacosx-version-min=10.13 -std=gnu++14 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -D_HAS_AUTO_PTR_ETC=0 -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/BH/include' -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/Rcpp/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c pk_1cmt_iv_infusion.cpp -o pk_1cmt_iv_infusion.o
pk_1cmt_iv_infusion.cpp:20:30: warning: …
```
=> RXR-1689 Fix warnings in linear models upon installation

R/new_covariate.R, man/new_covariate.Rd, tests/testthat/test_new_covariate.R
There was a unique situation that was not being handled correctly: 
- if the value supplied was non-numeric and 
- the `remove_negative_times` argument was `TRUE` (default), and 
- there were negative times, with the non-numeric value changing on either side of `t = 0`
then we were not actually carrying the last observation forward, but instead filtering the observations.
This is a pretty niche situation (`PKPDsim::sim`, the intended consumer of this data object requires numeric values) but when these values are used as placeholders for later use it was leading to some confusing results.
For safety, I also added a check to ensure the implementation method specified matches what we say in the documentation are the acceptable input types.
=> use LOCF when non-numeric too; check for implementation type

R/create_event_table.R, R/new_regimen.R, tests/testthat/test_create_event_table.R, tests/testthat/test_new_regimen.R
In create_event_table, two changes were necessary to enable simultaneous infusion-type doses in different compartments.
1) needed to assume that infusion doses could have a "type" other than "infusion". Changed logic to reference `t_inf`, assuming the user specified this correctly as non-zero.
2) needed to fix logic to also consider dose cmt when looking for duplicated rows
Added a test too
=> rm assumption non-inf types are t_inf = o

R/create_event_table.R, R/new_regimen.R, tests/testthat/test_create_event_table.R, tests/testthat/test_new_regimen.R
Removes logic that forces `type` to be one of 'bolus', infusion', 'oral', 'sc' or 'im'. If `type` is `NULL` we will still assume it's infusion if there's a `t_inf`, bolus otherwise.
=> RXR-1771: Remove constraints on regimen type

R/create_event_table.R, tests/testthat/test_create_event_table.R
We were getting errors for a regimen that was a mix of bolus and sc doses. `t_inf` for the boluses was being set to 0, but for sc it was `NA`. This led to an error at line 129. I made two changes: added sc and im to the vector of types whose infusion length should be set to 0. Also added `na.rm = TRUE` at line 129 for greater safety.
=> RXR-1771: Include sc, im among types whose t_inf should be 0

inst/models/pk_busulfan_mccune.json5, inst/models/pk_busulfan_shukla.json5
This PR adds two new models to our open source model library: the McCune model and the Shukla model. Both models have been previously published (citation in model files) and were used as part of a comparison of NCA and MAP approaches to AUC estimation presented at IATDMCT 2022 (Prague).
=> busulfan models: mccune and shukla

R/merge_regimen.R, tests/testthat/test_merge_regimen.R
When merging multiple regimens, if the Nth regimen does not have an infusion time specified, that value should be 0, and if it is specified, that value should be used. The logic was incorrectly set up here, and would impact regimens where Nth regimens were infusion (or, not oral/bolus).
=> fix error in infusion length merges

R/join_regimen.R, tests/testthat/test_join_regimen.R
When joining regimens using `t_dose_update`, only the `rate` values from the first regimen were included, and the value in `n` was incorrect. This fixes both.
=> Fix `n` and length of rate vector in regimens joined by t_dose_update

R/compile_sim_cpp.R, inst/cpp/sim.cpp, tests/testthat/test_timevar_cov.R
Time-varying covariates were only really interpolated when they were included in the `ode` block, and not when in the `pk` block. E.g. compare:
Not working previously:
```
code = "
dAdt[1] = -(Q/V)*A[1] + (Q/V2)*A[2] -(CLi/V)*A[1];
dAdt[2] = -(Q/V2)*A[2] + (Q/V)*A[1];
",
pk_code = "CLi = CL + CRCL",
```
Working fine:
```
code = "
CLi = CL + CRCL
dAdt[1] = -(Q/V)*A[1] + (Q/V2)*A[2] -(CLi/V)*A[1];
dAdt[2] = -(Q/V2)*A[2] + (Q/V)*A[1];
"
```
In the output from `sim()` it looked as if covariates were actually interpolated over time, but the interpolated value was not actually applied in the PK calculations. The covariates were still changing over time, but always using the value of the last change (similar to `locf` method).
This PR fixes the behavior, i.e. it executes the code that calculates …
=> RXR-1884: timevarying covariates were not interpolated when in PK block

R/apply_duration_scale.R, tests/testthat/test_apply_duration_scale.R
I was trying to follow the logic in this function, since there are a lot of different combinations of arguments accepted. I added a few tests as examples of ways to supply these arguments, increasing the test coverage of the file to 100%.
I found what I think is an error: an addition should have been changed to a multiplication.
=> add tests, plus to multiplication

DESCRIPTION, R/PKPDsim-package.R, R/create_event_table.R, man/PKPDsim-package.Rd, tests/testthat/test_create_event_table.R
I was running a simulation and encountered an uninformative error message. I was able to track down the source but it took me a while since the error was very generic:
>Error in vapply(regimen$type, function(x) cmt_mapping[[x]], FUN.VALUE = numeric(1),  : 
values must be length 1,
but FUN(X[[1]]) result is length 0
Having this extra check and more informative error message would have saved me some time.
=> add informative error message to facilitate debugging

DESCRIPTION, R/new_regimen.R, tests/testthat/test_new_regimen.R
Added t_inf argument to new_regimen() and adapted tests.
=> add t_inf to sc doses in new_regimen

.github/workflows/R-CMD-check.yaml, R/new_ode_model.R
The command
```
PKPDsim::install_default_literature_model("pk_busulfan_mccune")
```
wasn't working because in `new_ode_model()` it tried to run a command like
```
R CMD INSTALL --arg1 --arg2 C:\Users\User name\etc
```
So the space in the path actually split that argument into two arguments, and hence made the installation fail. The fix just adds double-quotes around that argument to ensure it is parsed as a single argument. After this, the package installed fine. 
Hopefully this fixes the issue (https://github.com/InsightRX/mipdtrial/actions/runs/9473553934/job/26101414203) with mipdtrial, although from the error there it doesn't seem like that path actually contained a space...
The change shouldn't affect behavior on Linux or Mac, in fact it is safer there too.
=> ensure paths with spaces are parsed properly

R/sim.R, tests/testthat/test_iov.R
See description of [change in Rcpp](https://github.com/RcppCore/Rcpp/issues/1311#user-content-fn-1-1400efc2b2c5361907ad0f063feeeb20).
The failure in PKPDsim test was due to an erroneously configured test case, which had the wrong number of bins for simulation of inter-occasion variability. This led to extra warnings using the new Rcpp. This PR fixes the test case. 
It also adds an extra warning to make it harder to misconfigure the number of IOV bins (and a new test to confirm the warning is thrown). I did not make that a hard stop(), because in most cases the misconfiguration is not affecting the results.
For reviewing this PR: 
1. first run tests using old version of Rcpp (anything before 1.0.12.4). The tests should all run fine, either on master or on this branch.
2. then install …
=> RXR-2140: fix issue due to change in warning behavior in upcoming Rcpp

R/regimen_to_nm.R, tests/testthat/test_regimen_to_nm.R
Refactor of the logic around throwing a warning around infusion rates. This was throwing a harmless but unnecessary warning during automated model validations for some models.
The logic was too strict, it was also thrown for regimens where infusion rates were not relevant. The logic is updated and simplified, as well as the warning text. Also added a test (there was already one test, updated that one too). The warning 
is not thrown any more in the model validation where it occurred before.
=> RXR-1876 fix warning infusion

Dockerfile, Dockerfile.aws, docker-compose.yml
This PR updates the Dockerfile to use the public `rocker/r-ver` image instead of the previously specified private image. This change simplifies the build process by using a widely-available base image specifically designed for R, which is maintained by the R community.
1. **Base Image Update**:
- Changed the base image to `rocker/r-ver:latest`. This image is optimized for R and maintained by the Rocker Project, ensuring compatibility and ease of use.
2. **System Dependencies**:
- Added installation commands for system dependencies `pandoc` and `qpdf` required by the package.
- Included clean-up commands to reduce the final image size.
3. **CRAN Packages Installation**:
- Added commands to install necessary CRAN packages (`mockery`, `nlmixr2`, `knitr`, `rmarkdown`) from the cloud …
=> Update Dockerfile to Use Rocker R Image

.github/workflows/pkgdown.yaml, DESCRIPTION, R/compile_sim_cpp.R, R/sim.R, man/sim.Rd, tests/testthat/test_iov.R
It was creating an array that was unneccessarily large due to a typo. 
With this update, the behavior is only harmless when the requested number of bins is _lower_ then the number of bins that were originally defined for the model. However, if the number of requested iov bins is _higher_ than defined for the model, it would lead to a runtime error at the C++ level, since it would try to use a vector element that is not defined.
I have changed the behavior now to throw a warning for the harmless case, and an error (at the R level) for the problematic case. Have updated documentation as well. No C++ level errors should occur anymore.
=> RXR-2224: fix indexing issue iov bins

PKPDsim.Rproj, inst/cpp/sim.cpp, tests/testthat/test_sim.R
In the core `sim()` function there was an edge case where dose-dependent variables or parameters were not correctly initialized, being either NA or a wrong value. Dose-dependent variables are usually implemented using the built-in `prv_dose` variable that updates whenever a new dose is given. For the first initialization step (before looping through the event record), this was previously getting set to the first value in the `dose` column of the event record. But the first row of the event record is never a dosing record, but an initialization row to make sure variables are correctly set, so it will never hold the value of the dose. Therefore the `prv_dose` value upon initialization was always set to 0.
This fix improves that by finding the first dose record (evid == 1) in the event …
=> fix handling of dose-dependent parameters

PKPDsim.Rproj, R/sim.R, tests/testthat/test_iov.R
This occurs when specifying IOV bins when not implemented. It will throw a low-level warning, but after that it will also cause a memory access failure that causes R to abort the session.
This PR should fix this, added a test for it as well that failed previously. I've chosen to make this an error and not a warning since this is important to get right, so IMO better than e.g. throwing a soft warning and ignoring the `iov_bins` argument.
=> RXR-2577 fix memory access issue 

R/create_event_table.R, R/new_regimen.R, tests/testthat/test_create_event_table.R, tests/testthat/test_new_regimen.R
`new_regimen()` will now use regex to look for the word "oral" instead of requiring an exact match to the word "oral", allowing the same t_inf adjustments for any type with "oral" in it (e.g., "oral_tablet", "oral_suspension").
I also noticed that we had conflicting logic for SC and IM dosing, where in `new_regimen()` we explicitly test for non-0 infusions for SC while in `create_event_table()` we forced these to be 0. I resolved this conflict by allowing SC and IM dosing to have non-zero t_inf.
=> RXR-2590: add support for additional "types" of oral dosing

R/sim.R, tests/testthat/test_sim.R
We allow the argument t_init to be specified in the case of observations prior to the first dose. When this occurs, we shift the regimen start time to begin at t_init, effectively changing the "origin". However, we were not also shifting covariate times. As a result, there could be a mismatch in covariate times and dose times in simulation.
I opted to call PKPDsim::new_covariate again to update the covariate times since this ensures the covariate values are correctly extrapolated backwards to t = 0, respecting existing implementation method for extrapolation.
=> RXR-2593: Ensure covariate times are correct when t_init is non-zero

R/sim.R, man/sim.Rd
This PR updates documentation to provide clarifications on the use of the mixture group argument. See https://github.com/InsightRX/PKPDmap/pull/48
=> RXR-2666: clarify documentation for mixture_group argument

R/create_event_table.R, R/sim.R, tests/testthat/test_sim.R
This PR ensures we correctly adjust t_obs and covariate times for both t_init and t_ss. Previously, we were only adjusting for t_init.
I made more lines of code changes than strictly necessary so that it is easier to track which time-containing variables are adjusted when. We had been inconsistently adding t_init and t_ss, and now we should generally be adjusting for one or both at the same time, as appropriate.
I opted to keep t_init and t_ss as separate variables rather than lumping them together as one variable (e.g., t_rezero or something) because it allows for better partitioning of the sources of time adjustments. we do handle them separately in a couple places.
I added some comments throughout to clarify locations that I found confusing. I also added quite a few unit tests for …
=> RXR-2789: also adjust covariate times to account for prepended steady-state dosing

R/sim.R, tests/testthat/test_sim.R
This PR fixes a small bug introduced in https://github.com/InsightRX/PKPDsim/pull/123 for steady-state regimens where t_init != 0 and there was an observation before t == 0. We were filtering these observations out of the output, but we want to retain them.
=> RXR-2811: fix time shift bug introduced in RXR-2789
